// <auto-generated />
using System;
using HausSalesBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HausSalesBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240601062414_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HausSalesBackend.Models.GeneralLedger", b =>
                {
                    b.Property<Guid>("glId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("glAccDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("glAccName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("glGroupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("glTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tempAccName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("glId");

                    b.ToTable("GeneralLedgers");
                });
#pragma warning restore 612, 618
        }
    }
}
